services:
  tunnel:
    container_name: cloudflare
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=enter_tunnel_token_here
    networks:
      - tunnel

  headscale:
    image: headscale/headscale:latest
    container_name: headscale
    restart: unless-stopped
    volumes:
      - ./config:/etc/headscale
      - ./data:/var/lib/headscale
    ports:
      - 8080:8080
      - 9090:9090
    command: serve
    networks:
      - tunnel

networks:
  tunnel:
    driver: bridge
